language: csharp
dist: xenial
mono: none
dotnet: 2.2
install:
- dotnet restore src/ParkMate/
script:
- dotnet build src/ParkMate/
- dotnet test src/ParkMate/Web.Tests/Web.Tests.csproj
- dotnet test src/ParkMate/ApplicationCore.Tests/ApplicationCore.Tests.csproj
